### ISSUE TITLE
RTSP Stream runs only for 10 seconds

### ISSUE THREAD

**Issue by kanehekili** [damianhoppe/RTSP-Player#14]
Running against the mediamtx server the app displays a strange behavior: It connects, runs for about 10 seconds, then freezes. No more frames.
Checking the logs of my server does not show anything. 

Concurrent testing with ffplay on a linux device shows the the stream is still up and running.

**Comment by damianhoppe** [comment]
I was able to reproduce the problem.
It seems that the problem is the OpenGL player and disabling it solves the problem. The "Surface of player" option is responsible for this change, which should be changed to "No OpenGL".
At the moment, this is probably the only solution.
A future update should fix this problem.

**Comment by damianhoppe** [comment]
The new update has been made available on Google Play and is also available in the releases tab of the repository.
Video stuttering/performance issues should probably be fixed.
Support for the ExoPlayer library has also been added as an alternative to the VLC library.

I encourage you to test it and ask for feedback if problems persist.

**Comment by kanehekili** [comment]
Thanks for the swift response. I will need to set up the camera again, test it and will report back

**Comment by kanehekili** [comment]
The fix runs on my devices, I've updated to 5 Stars and will close this
