### ISSUE TITLE
Add place holders for multiples cameras

### ISSUE THREAD

**Issue by manuelcanepa** [damianhoppe/RTSP-Player#5]
Maybe we can have a kind of placeholder with the index of the camera, this will be usefull when you need to add multiples cameras at once. I was thinking something like on the input:

`rstp://user@192.168.0.1:552/ch{{number}}`

And some extra fields like: 
`
First camera: [min_index]
Qty of camera: [qty]
`

So, if you have to add 3 cameras with numbers 5, 6 and 7 you can set the config:

`
First camera: [5]
Qty of camera: [3]
`

Grouped cameras #6
Additional, the cameras can be grouped and config once. Most of the time, this app will be use to add a serie of cameras with just a little change, other config will remain the same. In my case, i have 8 camera on my dvr, and if need to change the user, password or the IP is required to do it 8 times.

**Comment by Huczeq** [comment]
A very interesting idea, after a reflection I came to this solution:
- the user will be able to create a group of cameras by adding a special code to the form (no matter in what field), which will be a placeholder
- you will be able to create placeholders in almost every field of the add / edit camera form, except for the name
- in the camera name field you will be able to display the contents of the placeholder (so that the camera names differ)
- creating a placeholder will consist of setting the name (optionally, if not set, it will be generated automatically) and the value
- editing one camera in the group will update the data for each camera in the group

Examples of placeholders:
1. Single values: {number = 1,2,3} - 3 cameras will be generated: 1,2,3
2. Ranges: {number = 4-8} - 5 cameras will be generated: 4,5,6,7,8
3. First and length: {number = 4/10} - 10 cameras will be generated with an initial value of 4: 4,5,6,7,8,9,10,11,12,13

All the above structures can be combined into one, for example:
{number = 1,2,3-9,10 / 10} - 20 cameras will be generated

This idea will not use additional fields, which will facilitate implementation at the moment, and in the future it will be possible to think about extending it to create additional fields in the form for placeholders.
What do you think about it?

**Comment by manuelcanepa** [comment]
I want to help, but i dont know how to start to debug the project, i just clone the code and when i try to start Android Studio say:

```
AAPT: error: failed writing to '...\RTSP-Player\app\build\intermediates\runtime_symbol_list\debug\R.txt': The data is invalid. (13).
```

**Comment by Huczeq** [comment]
Try to clean the project (Build-> Clean Project).
If that doesn't work, check that your antivirus is not blocking access to the file. :D

**Comment by Huczeq** [comment]
Hello
I have released a new beta version which has the camera group creation system finished.
The solution itself is slightly different from the one I presented before, but it is just as useful.
Now you can add variables by setting the variable name and value, (for example: "1,2,3", "1/2" or "1-3").
Variables can be used in all of the above fields by: {variableName}.

You can find the application here:
https://github.com/Huczeq/RTSP-Player/releases/tag/pre1.7-16
In some time there should be a new, official version available on Google Play.

**Comment by damianhoppe** [comment]
Implemented 🏆
The update has been made available on Google Play and in the releases tab of the repository

**Comment by damianhoppe** [comment]
Implemented 🏆
The update has been made available on Google Play and in the releases tab of the repository
